name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: WillAbides/setup-go-faster@v1.6.0
      id: setup-go-faster
      with:
        go-version: "*"

    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
      if: ${{ runner.os == 'Linux' }}

    - name: Build (Linux & MacOS)
      run: go build -tags ci -ldflags "-X main.BuildDate=`date +%Y-%m-%d`" -o build/ .
      if: ${{ runner.os != 'Windows' }}
    
    - name: Build (Windows)
      run: go build -tags ci -ldflags "-s -w -X main.BuildDate=$(Get-Date -format 'u')" -o build/ .
      if: ${{ runner.os == 'Windows' }}
    
    - name: Install fyne
      run: go get fyne.io/fyne/v2/cmd/fyne
    
    - name: Package (Linux)
      run: fyne package -release -executable build/anarchy-droid && ls -l && mkdir pkg && mv anarchy-droid.tar.* pkg/
      if: ${{ runner.os == 'Linux' }}
      
    - name: Package (macOS)
      run: fyne package -release -executable build/anarchy-droid && mkdir pkg && mv anarchy-droid.app pkg/
      if: ${{ runner.os == 'macOS' }}
    
    - name: Package (Windows)
      run: fyne package -release -executable build/anarchy-droid.exe && mkdir pkg && mv anarchy-droid.exe pkg/
      if: ${{ runner.os == 'Windows' }}
    
    - uses: actions/upload-artifact@v2
      with:
        name: Anarchy-Droid-${{ runner.os }}-pkg
        path: pkg
    
    - uses: actions/upload-artifact@v2
      with:
        name: Anarchy-Droid-${{ runner.os }}
        path: build